version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
  - dependency-name: actionpack
    versions:
    - 6.1.2.1
  - dependency-name: jbuilder
    versions:
    - 2.11.2
